In [1]:
import numpy as np
array = np.array([1,2,3,4,5,6,])
newArray = array.reshape(2,3)
print(' 1D Numpy array:')
print(array)
print('2D Numpy array')
print(newArray)

 1D Numpy array:
[1 2 3 4 5 6]
2D Numpy array
[[1 2 3]
 [4 5 6]]
